MarvelCharacters/config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :characters, only: [:index, :new, :create, :show]
  resources :comics, only: [:index, :show]
  
  get "api/characters", to: "api#characters", as: "api_characters"
  get "api/characters/:id", to: "api#character", as: "api_character"
  get "api/comics", to: "api#comics", as: "api_comics"
  get "api/comics/:id", to: "api#comic", as: "api_comic"
  get "api/search/", to: "api#search", as: "api_search"

  get "search", to: "search#search"
  get "search_error", to: "search#error"

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

MarvelCharacters/app/models/comic.rb
require 'elasticsearch/model'

class Comic < ApplicationRecord
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks

    has_many :occurences
    has_many :characters, :through => :occurences
    
    validates :title, :marvel_id, presence: true
    validates :marvel_id, uniqueness: true
    validates :marvel_id, numericality: { only_integer: true }
end

MarvelCharacters/app/controllers/comics_controller.rb
class ComicsController < ApplicationController
    def index
        @comics = Comic.all
    end

    def show
        @comic = Comic.find(params[:id])
    end
end
  

MarvelCharacters/app/views/comics/index.html.erb
<div class="container">
  <h1>Listing comics</h1>
  <p>
    Click <%= link_to "here", controller: "api", action: "comics" %> to access the API end-point to get the raw data (json)!
  </p>

  <p>
    <h>Total Comics: <%= @comics.length %></h>
  </p>

  <% @comics = @comics.sort_by{ |t| t.title}  %>  
  <% @comics.each do |comic| %>
    <p>
      <td><%= link_to comic.title, comic_path(comic) %></td>
    </p>
  <% end %>
</div>

MarvelCharacters/app/views/comics/show.html.erb
<div class="container"> 
  <p>
    Click <%= link_to "here", controller: "api", action: "comic", id: @comic.id %> to access the API end-point to get the raw data (json)!
  </p>
  
  <p>
    <p>
      <h1> <%= @comic.title %> </h1>
    </p>
    <p>
      <h><%= image_tag @comic.image_path %></h>
    </p>
    <p>
      <h>Marvel ID: <%= @comic.marvel_id %></h>
    </p>
    <p>
      <h>Issue Number: <%= @comic.issue_number %></h>
    </p>
    <p>
      <h>Modified: <%= @comic.modified %></h>
    </p>
    <p>
      <h><%= @comic.description %><h>
    </p>
  </p>
</div>