MarvelCharacters/config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :characters, only: [:index, :new, :create, :show]
  resources :comics, only: [:index, :show]
  
  get "api/characters", to: "api#characters", as: "api_characters"
  get "api/characters/:id", to: "api#character", as: "api_character"
  get "api/comics", to: "api#comics", as: "api_comics"
  get "api/comics/:id", to: "api#comic", as: "api_comic"
  get "api/search/", to: "api#search", as: "api_search"

  get "search", to: "search#search"
  get "search_error", to: "search#error"

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

MarvelCharacters/app/controllers/search_controller.rb
class SearchController < ApplicationController
    def search
        if params[:term].nil?
            @characters = []
            @comics = []
        else
            @characters = Character.search params[:term], :size => 100
            @comics = Comic.search params[:term], :size => 100
            @query = params[:term]
        end

        # Will fail if Elasticsearch service is not running on port 9200
        begin
            @characters.size
        rescue
            redirect_to search_error_path
        end
    end

    def error
    end
end

MarvelCharacters/app/views/search/_form.html.erb
<%= form_for :term, url: search_path, method: :get do |form| %>
    <p>
        <%= text_field_tag :term, params[:term] %>
        <%= submit_tag "Search", name: nil %>
    </p>
<% end %>

MarvelCharacters/app/views/search/error.html.erb
<div class="container">
    <h1>Oooops!</h1> 
    <p>
    <h>It seems we had a problem while performing the search. ;(</h> 
    </p>
    <h> You should try again later.</h>
</div>

MarvelCharacters/app/views/search/search.html.erb
<div class="container"> 
    <h1>Search Results</h1>
    <p>
        A maximum of 100 hits can be displayed for each category (Character and Comic)
    </p>
    <p>
        Got a total of <%= @characters.size + @comics.size %> hits for the query '<%= @query %>'
    </p>
    <p>
        Click <%= link_to "here", controller: "api", action: "search", term: @query %> to access the API end-point to get the raw data (json)!
    </p>
</div>

<div class="container">
    <% if @characters %>
        <p>
            <h>Characters: <%= @characters.size %> hits</h>
        </p>
        <ul class="search_results">
            <% @characters.each do |character| %>
                <p>
                    <h><%= link_to character.name, controller: "characters", action: "show", id: character._id %></h>
                </p>
            <% end %>
        </ul>
    <% else %>
        <p>Your search did not match any character documents.</p>
    <% end %>
</div>

<div class="container">
    <% if @comics %>
        <p>
            <h>Comics: <%= @comics.size %> hits</h>
        </p>
        <ul class="search_results">
            <% @comics.each do |comic| %>
                <p>
                    <h><%= link_to comic.title, controller: "comics", action: "show", id: comic._id %></h>
                </p>
            <% end %>
        </ul>
    <% else %>
        <p>Your search did not match any comic documents.</p>
    <% end %>
</div>